/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./index.html', './glossary.html'],
  safelist: [
    'text-gray-700',
    'bg-gray-800',
    'hover:bg-gray-700',
    'hover:bg-gray-200',
    'hover:bg-accent/90',
    'bg-accent/90',
    'bg-red-100',
    'text-red-800',
    'bg-cyan-100',
    'text-cyan-800',
    'bg-blue-100',
    'text-blue-800',
    'bg-green-100',
    'text-green-800',
    'bg-purple-100',
    'text-purple-800',
    'bg-orange-100',
    'text-orange-800',
    'bg-amber-100',
    'text-amber-800',
    'bg-pink-100',
    'text-pink-800',
    'bg-indigo-100',
    'text-indigo-800',
    'bg-emerald-100',
    'text-emerald-800',
    'bg-teal-100',
    'text-teal-800',
    'dark:bg-red-900',
    'dark:text-red-200',
    'dark:bg-cyan-900',
    'dark:text-cyan-200',
    'dark:bg-blue-900',
    'dark:text-blue-200',
    'dark:bg-green-900',
    'dark:text-green-200',
    'dark:bg-purple-900',
    'dark:text-purple-200',
    'dark:bg-orange-900',
    'dark:text-orange-200',
    'dark:bg-amber-900',
    'dark:text-amber-200',
    'dark:bg-pink-900',
    'dark:text-pink-200',
    'dark:bg-indigo-900',
    'dark:text-indigo-200',
    'dark:bg-emerald-900',
    'dark:text-emerald-200',
    'dark:bg-teal-900',
    'dark:text-teal-200',
    'dark:bg-gray-700',
    'dark:text-gray-200',
    'dark:bg-gray-800',
    'dark:text-gray-300',
    'dark:hover:bg-gray-700',
    'dark:bg-darkbg',
    'dark:text-darktext',
    'dark:bg-darksection',
    'dark:bg-darksection/90',
    'dark:bg-darksection/95',
    'dark:to-darksection/20',
    'dark:to-darksection/60',
    'dark:to-darksection/85',
    'dark:border-darkborder',
    'dark:border-darkborder/20',
    'dark:border-darkborder/50',
    'dark:text-background',
    'dark:text-background/60',
    'dark:text-background/70',
    'dark:text-background/80',
    'dark:hover:bg-background/10',
    'dark:hover:text-background',
    'dark:bg-accent/20',
    'dark:bg-main/20',
    'dark:border-accent/30',
    'dark:border-main/30',
    'dark:opacity-10',
    'dark:from-darkbg',
    'dark:via-darkbg',
    'dark:from-darksection/95',
    'dark:to-darksection/85',
    'dark:hover:bg-accent/90',
    'dark:bg-gray-600',
    'dark:hover:bg-gray-600',
    'dark:bg-gray-200',
    'dark:text-gray-200',
    'dark:bg-gray-700',
    'dark:text-gray-700',
    'dark:bg-gray-300',
    'dark:hover:bg-gray-300',
    'grid',
    'grid-cols-2',
    'grid-cols-3',
    'md:grid-cols-2',
    'lg:grid-cols-3',
    'xl:grid-cols-[1fr_450px]',
    'gap-6',
    'gap-1.5',
    'px-3.5',
    'sticky',
    'top-6',
    'h-fit',
    'backdrop-blur-sm',
    'translate-x-full',
    'translate-y-1/2',
    '-translate-y-1/2',
    'transform',
    'scale-105',
    'hover:scale-105',
    'z-40',
    'z-50',
    'z-60',
    'pointer-events-none',
    'pointer-events-auto',
    'opacity-0',
    'opacity-100',
    'opacity-5',
    'opacity-10',
    'opacity-20',
    'opacity-30',
    'opacity-50',
    'opacity-60',
    'opacity-70',
    'opacity-80',
    'opacity-90',
    'opacity-95',
    'opacity-8',
    'opacity-15',
  ],
  theme: {
    extend: {
      colors: {
        main: "#333333",
        background: "#FAF8F5",
        accent: "#FF6B35",
        tertiary: "#005271",
        sectionbg: "#FFF2EB",
        darkbg: "#1C1C1C",
        darksection: "#2A2A2A",
        darktext: "#F2F2F2",
        darktertiary: "#66BBD2",
        darkborder: "#444",
        darkgray: "#333",
      },
      fontFamily: {
        sans: ['Inter', 'Arial', 'sans-serif'],
      },
      fontSize: {
        'xs': ['0.7rem', { lineHeight: '1rem' }],
        'sm': ['0.8rem', { lineHeight: '1.25rem' }],
        'base': ['0.95rem', { lineHeight: '1.5rem' }],
        'lg': ['1.05rem', { lineHeight: '1.7rem' }],
        'xl': ['1.15rem', { lineHeight: '1.75rem' }],
        '2xl': ['1.4rem', { lineHeight: '2rem' }],
        '3xl': ['1.75rem', { lineHeight: '2.25rem' }],
        '4xl': ['2rem', { lineHeight: '2.5rem' }],
      },
      opacity: {
        '8': '0.08',
        '15': '0.15',
      },
    },
  },
  plugins: [],
} 